/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIdIndexRouteImport } from './routes/opportunities.$id.index'
import { Route as OpportunitiesIdGraphRouteImport } from './routes/opportunities.$id.graph'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdIndexRoute = OpportunitiesIdIndexRouteImport.update({
  id: '/opportunities/$id/',
  path: '/opportunities/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdGraphRoute = OpportunitiesIdGraphRouteImport.update({
  id: '/opportunities/$id/graph',
  path: '/opportunities/$id/graph',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/opportunities/$id/graph': typeof OpportunitiesIdGraphRoute
  '/opportunities/$id/': typeof OpportunitiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/opportunities/$id/graph': typeof OpportunitiesIdGraphRoute
  '/opportunities/$id': typeof OpportunitiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/opportunities/$id/graph': typeof OpportunitiesIdGraphRoute
  '/opportunities/$id/': typeof OpportunitiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/login'
    | '/opportunities/$id/graph'
    | '/opportunities/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/login'
    | '/opportunities/$id/graph'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/login'
    | '/opportunities/$id/graph'
    | '/opportunities/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  LoginRoute: typeof LoginRoute
  OpportunitiesIdGraphRoute: typeof OpportunitiesIdGraphRoute
  OpportunitiesIdIndexRoute: typeof OpportunitiesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id/': {
      id: '/opportunities/$id/'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id/'
      preLoaderRoute: typeof OpportunitiesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id/graph': {
      id: '/opportunities/$id/graph'
      path: '/opportunities/$id/graph'
      fullPath: '/opportunities/$id/graph'
      preLoaderRoute: typeof OpportunitiesIdGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  LoginRoute: LoginRoute,
  OpportunitiesIdGraphRoute: OpportunitiesIdGraphRoute,
  OpportunitiesIdIndexRoute: OpportunitiesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
